name: Continuous Deployment

on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
  
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
        
      - name: Extract tag name
        id: tag
        run: echo "TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Build and Push Multi-Platform Docker Image
        run: |
          docker buildx build --platform linux/amd64,linux/arm64 -t ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_IMAGE_NAME }}:${{ env.TAG }} . --push

      - name: SSH and deploy app
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            docker rmi -f $(docker images -aq)
            docker pull ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_IMAGE_NAME }}:${{ env.TAG }}
            docker run -dp ${{ secrets.DOCKER_CONTAINER_PORT_2 }}:${{ secrets.DOCKER_IMAGE_PORT }} --name ${{ secrets.DOCKER_CONTAINER_NAME_2 }} -e NODE_ENV=${{ secrets.NODE_ENV }} -e PORT=${{ secrets.PORT }} -e IS_HTTPS=${{ secrets.IS_HTTPS }} -e JWT_SECRET_KEY=${{ secrets.JWT_SECRET_KEY }} -e DATABASE_URL=${{ secrets.DATABASE_URL }} ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_IMAGE_NAME }}:${{ env.TAG }}

            for i in {1..10}; do
              if curl -s http://localhost:${{ secrets.DOCKER_CONTAINER_PORT_2 }}/health; then
                echo "${{ secrets.DOCKER_CONTAINER_NAME_2 }} is healthy!";
                exit 0
              fi
              sleep 3
            done
            exit 1
      
      - name: Promote if health check passed
        if: success()
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            docker stop ${{ secrets.DOCKER_CONTAINER_NAME_1 }} || true
            docker rm ${{ secrets.DOCKER_CONTAINER_NAME_1 }} || true
            docker rename ${{ secrets.DOCKER_CONTAINER_NAME_2 }} ${{ secrets.DOCKER_CONTAINER_NAME_1 }}
            sudo nginx -s reload
      
      - name: Rollback if health check unpassed
        if: failure()
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            docker stop ${{ secrets.DOCKER_CONTAINER_NAME_2 }} || true
            docker rm ${{ secrets.DOCKER_CONTAINER_NAME_2 }} || true
