name: Continuous Integration

on:
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v2
      
      - name: Install dependencies
        run: npm install
      
      - name: Eslint
        run: npm run lint
      